services:
  sql-server:
    image: "mcr.microsoft.com/mssql/server:latest"
    ports:
      - 1433:1433
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abcd1234.
      - MSSQL_PID=Developer 
